### ISSUE TITLE
No signatures found matching the expected signature for payload

### ISSUE THREAD

**Issue by abaybektursun** [vercel/nextjs-subscription-payments#228]
I followed the Readme step by step multiple times and tried test only and production.
It was never able to connect to Stripe. 
Here is the error in the Vercel Logs:

Function `/api/webhooks`

```
❌ Error message: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? 
Learn more about webhook signing and explore webhook integration examples for various frameworks at https://github.com/stripe/stripe-node#webhook-signing
```

**Comment by abaybektursun** [comment]
I changed the code to `const sig = req.headers.get('stripe-signature');`
The warning message is gone, however, it still says No subscription pricing plans found.

**Comment by commandcenterio** [comment]
I'm facing the same issue

**Comment by commandcenterio** [comment]
Spent all day reading old threads and attempting the recommended fixes, no luck.
Has anyone resolved this error?

**Comment by commandcenterio** [comment]
@thorwebdev  @leerob any insight?

**Comment by abaybektursun** [comment]
@thorwebdev ? ^

**Comment by commandcenterio** [comment]
My issue was that i was using the incorrect secret

**Comment by haramishra** [comment]
"For me, when I pasted the key on vercel, it added a new line, which caused the error. I removed the new line, and the error was fixed.

**Comment by ebowwa** [comment]
the pr seems to have been committed to main, and im updated to the most recent push; however, im still facing this exact issue, even with `const sig = req.headers.get('stripe-signature') as string;` in the app/webhooks/route.ts

**Comment by Asrover** [comment]
Stripe example how to use with NextJS:
https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/nextjs/pages/api/webhooks.ts
